name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Restore tools
      run: dotnet tool restore
    - name: Fornax build
      run: dotnet fornax build
    - name: Deploy
      uses: Peaceiris/actions-gh-pages@v3
      with:
          deploy_key: ${{ secrets.PAGES_DEPLOY_KEY}}
          publish_dir: ./_public
          publish_branch: live
          force_orphan: true
